# Generated by Django 5.2.12 on 2026-03-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_books', to='basic_api.profile')),
                ('profile_bouldering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bouldering', to='basic_api.profile')),
            ],
        ),
    ]
