# Generated by Django 5.2.12 on 2026-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('job', 'job'), ('school', 'school')], max_length=10)),
                ('align_description', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
            ],
        ),
    ]
