# Generated by Django 5.2.12 on 2026-03-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0003_timelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='period',
            field=models.CharField(default='any', max_length=200),
            preserve_default=False,
        ),
    ]
